=  Compteurs , numero Chrono


But: offrir une api permettant d'avoir un compteur d'horodatage ayant les caractéristique suivante :

- nomé, car besoin de plusieur compteur
- unique
- pouvant être en partie re-initialise en debut d'année par exemple un compteur de type yyyyMMdd#### ou les y = année sur 4 digits, MM=> mois sur 2 digits, d=> jour sur 2 digits, #### => nombre sur 4 digits incrémenté, et remis a zero en debut d'année
- non resetable (ex id)

== manque actuel

- des log !!


== Table de représentation explorer.chrono

- created : date de creation
- name: un nom unique (32 char max)
- resetMode : mode de resatage de compteur * pour manuel (auto), y pour année (remis a zero en debut d'année), m pour mois (voir année), d pour jour (voir année)
- lastResetdate : date de la dernière remise à zero
- counterPrefix : prefix du conteur au format date, ex : "'BL-'yyyyMMdd-"
- counterSuffix : suffixe du conteur au format date ex : ""
- counterNbDigit: nb digit 

- counter : le dernier conteur entier
- chrono : le dernier chrono  (String) retourné
- updateDate : date de derniere utilisation



== Java Api attendu 

- nextChrono(non chrono) : retournoure la chaione chrono represantant le numero de chrono suivant, et le considere comme utilisé. en interne influence sur counter, lastCounter lastCounter
- lastChrono(non chrono) : retoune la chaine representant le dernier chrono utilisé . a utiliser avant nexChrono()
- resetCounter(non chrono) ; remet a zero le conteur
- setCounter(non chrono, value) ; remet a value le conteur
- getCounter(non chrono) : retourn le conteur actuel 



== Macro langage API attendu

- @Chrono.next(non chrono)
- @Chrono.reset(non chrono)
- @Chrono.lastChrono(non chrono)



== Service attentue :

verbes :

- List : liste des chronos : id, nom, lastChrono
- Get : recuperation des info chrono (oute de la table ?)
- del : supprime un chrono, a utiliser avec parsimonie
- Add : creer un nouveau chrono, en verifiant que le nom est unique
- set : met a jour les info du chrono
- reset : reinitialisre un chrono (conteur mis a zero)

le format de sortie est en json, non compres ex pouiir l'ordre "Get"
[langage:json]
----
{
    code:"0", msg:"Ok",
    chrono:{
        idChrono: 1,
        name: "nom chrono",
        lastChrono: "",
        type: "year",
        format: "'BL-yyyyMMdd-@@@@",
        lastResetdate: 214345364,
        counter: 45,
        lastCounter: 45,
        lastChrono: "BL-20210112-0045"
    }
}
----

Page HTML

