= dos tech sur statistique, Dashboard


Dans l'idée :
- on creer des requette de selection de document du genre :

[source,sql]
----
            SELECT el.*
                FROM Explorer.EventLog el 
                WHERE el.created>'2020-01-01'
                    AND idAuthor=?
                ORDER BY el.created DESC
                LIMIT 100'
----

Sel la selection idAuthor, doit etre une option car un requete est que pour la personne en question
ou sur tous les personne (pour admin) ...


== Structure des tables de config :

=== table de requete

. Table des reqetes "Explore.query"

- name : un nom
- type: un type de requete : 

    * extraction sur les log "eventLog" avec comme choix les transition, l'etat d'arrivé, ajouté, deplacé, supprimé,, lue, téléechargé 
    * sur l'etat actuel des documents (present ) comme l'etat des doc, la date d'etat, de fichier la taille ou un formulaire et un champ des formulaire
- beginDate: une date de debut codé sous la forme de <type><temps>. Ou "type" est le type de date :

        * N pour date exacte
        * C pour calculé, et temps comme "y/m/d" ou chaque lettre represente le nombre de année,mois,jour à  ajouter/supprimer pour l'année, le mois et le jour dans la a partir de la date actuel : +
            ex 0/-1/1 => annee/(mois-1)/1 si mois<1 alors 1, si mois >12 alors 12, si jour<1 alors 1 si jour >find de mois alors finde mois +
            pour calculé, et temps comme "0/0/0|0/0/-7" les valeur suivant le "|" sont ajouter a la date caclule, mais cette fois en depassant du mois ou de l'anne , ainsi "0/0/0|0/0/-7" indique la date actuel moins 7 jours
          
- endDate : une date de fin codé comme la date de debut


. tables des donnée a selectionner (clause where) "Explorer.queryWhereAndData"

- enventNames : liste des event a prendre ex fileAdd, fileDel, DocStateChange, docStateChange
- tgt : dossier cible (pour le move c'e'st le dossier de destination)
- idUsers : identifiant des utilisateurs a prendre (virgule les separe), d'un profile (Pid), actuel (*) , ou tous (vide)
- state (si existe) :
    * DocStateChange : data1 (transition), data2 (etat destiantion)
    * docStateChange : data1 (etat1), data2 (etat destination)

=== Evenement de temps

. table exeplorent.timeEvent

- title: un nom
- date : quand le lancer: 1 fois par jour, tt les lundi , debut de mois ... +
    exemples : 
    * 0/0/1 => le 1er de mois 
    * 0/0/31 => dernier jour du mois !
    * 0/0/15 => 15 du mois !
    * 0/0/0|0/1 => toute les semaine le 1 jour (lundi)
    * 0/0/0|2/w1 => 2me semine du mois et 1 jour de la semain    
- time : heure de lancement par raport a la date sous la forme HH:mm


. table exeplorent.timeEventData

- idTimeEvent
- type : macro requete, mail
- data

but envoi :
par mail du nb ddoc traite dans la jouren : ajouter, transition, et status
par mail doc a traiter demain : doc dans un dossier donner pour un utilisateur donne ou profile
facture en payer imperativement date de facture + 30> date du jour
si selection une requete
type=query
data=> idQuery

== Dashboard

creation d'un dashboard :
    bt ajout un query
        un text au dessus
        affichage du query :         type affichage conteur, liste, compte + list
        un texte dessous
        
    
- une date de fin

== exemple de ce que l'on veux :

Sur log
----
SELECT
 count(idDoc) as "nbDoc"
 e.eventName as "eventName"
 e.author
 e.src, e.dst, e.tgt
FROM
 eventLog e
 IdLinkMap l ON l.idLinkMap=e.idDoc
 WSMemo m ON m.idWSUrl=l.idWSUrl
 WHERE e.....eventName=valide...
GROUP BY
    e.eventName
    e.idAuthor
    src ou dst ou tgt
----    

etat des doc
----
SELECT
 count(idWSUrl) as "nbDoc"
 e.docStateModified as "docStateModified"
 m.folder as "folder"
 
FROM
 WSMemo m 
 WHERE m. docStateModified...modified....
GROUP BY
    e.docState
    lastAuthor
    folder WSGetFolder(idWSUrl)
----
    
mail :

----
$@begin(@query1)$  $eventName$ : $nbDoc$<br> $@end$

$@begin(@quer2y)$  $docStateModified$ : $nbDoc$<br> $@end$
----